import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

import dynamic from 'next/dynamic'
const Map = dynamic(
  () => {
    return import('../components/map')
  }, 
  {ssr: false});

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Crowd Data Collection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"/>
      </Head>

      <main className={styles.main}>
        <h1 className="font-bold text-xl text-center">Welcome to T16 Crowd Data Collection</h1>
        <h3 className="text-lg text-center">Click Login to Continue</h3>
        <div className="mt-5 flex flex-row">
          <Link href="/login" passHref>
            <button className="block w-full px-3 py-2 mr-2 border bg-sky-500 hover:bg-sky-700 rounded-md shadow-sm text-sm leading-5 text-white font-semibold">Login</button>
          </Link>
          <Link href="/register" passHref>
            <button className="block w-full px-3 py-2 ml-2 border rounded-md hover:bg-slate-100 shadow-sm text-sm leading-5 font-semibold">Register</button>
          </Link>
        </div>
        <div className='m-5 w-1/3 h-1/3'>
          <Map></Map>
        </div>
      </main>
    </div>
  )
}

export default Home