import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Form from '../components/form'

const Login: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Crowd Data Collection - Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Form></Form>
            </main>
        </div>
    )
}

export default Login