import type { NextPage } from 'next'
import Head from 'next/head'
import Form from '../components/form'

const Login: NextPage = () => {
    return (
        <div className="p-8">
            <Head>
                <title>Crowd Data Collection - Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="min-h-screen p-16 flex flex-1 flex-col justify-center items-center">
                <Form></Form>
            </main>
        </div>
    )
}

export default Login